### ISSUE TITLE
fortnitepy.Client.close() spams the same asyncio exception 7 times

### ISSUE THREAD

**Issue by Londiuh** [Terbau/fortnitepy#108]
```log
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000272DC5CB700>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by Terbau** [comment]
After digging a little bit this seems like an issue with how aiohttp closes. With SelectorEventLoop (default asyncio loop < python 3.8), the error is apparently just logged. However, with ProactorEventLoop the error above is raised. The error has no affect on the closing process of fortnitepy clients and it is simply just noisy. I guess there's currently nothing else really to do than wait for an aiohttp update.
