### ISSUE TITLE
Error when importing module

### ISSUE THREAD

**Issue by stefanodvx** [Terbau/fortnitepy#151]
```
Traceback (most recent call last):
  File "C:\Users\Stefano\Desktop\UBOT\fn.py", line 1, in <module>
    import fortnitepy
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\fortnitepy\__init__.py", line 30, in <module>
    from .client import Client, run_multiple, start_multiple, close_multiple
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\fortnitepy\client.py", line 34, in <module>
    from aioxmpp import JID
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\aioxmpp\__init__.py", line 101, in <module>
    from .errors import (  # NOQA
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\aioxmpp\errors.py", line 90, in <module>
    from . import xso, i18n, structs
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\aioxmpp\xso\__init__.py", line 588, in <module>
    from .types import (  # NOQA: F401
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\aioxmpp\xso\types.py", line 46, in <module>
    from .. import structs, i18n
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\aioxmpp\i18n.py", line 48, in <module>
    import babel.dates
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\babel\dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\babel\util.py", line 20, in <module>
    from babel import localtime
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\babel\localtime\__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\babel\localtime\__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\babel\localtime\_win32.py", line 96, in _get_localzone
    return pytz.timezone(get_localzone_name())
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python39\lib\site-packages\babel\localtime\_win32.py", line 42, in get_localzone_name
    localtz = winreg.OpenKey(handle, TZLOCALKEYNAME)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
```

**Comment by realdoener** [comment]
Had this once too, changing my timezone and then changing it back helped. My registry keys for timezones were missing

**Comment by Terbau** [comment]
A bit late, but hopefully doener's fix helped you.
